name: On Dispatch Test

on:
  repository_dispatch:
    types: [run-pw-tests]
  workflow_dispatch: 

concurrency:
  group: e2e-tests
  cancel-in-progress: false

jobs:
  execute:
    runs-on: ubuntu-latest
    steps:

      - name: Report pending back
        if: github.event.client_payload.source_commit_sha != '' && github.event.client_payload.source_commit_sha != null
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.PAT_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.event.client_payload.source_repository}}/statuses/${{ github.event.client_payload.source_commit_sha }} \
            -d '{
                "state": "pending",
                "context": "Playwright Tests",
                "description": "This check has started...",
                "target_url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
              }'

      - name: Checkout Repository
        if: github.event.client_payload.target_branch != '' && github.event.client_payload.target_branch != null
        id: checkout-repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.client_payload.target_branch || 'main' }}

      - name: Pass or fail based on expected_status
        run: |
          sleep 60
          if [[ "${{ github.event.client_payload.expected_status }}" == "pass" ]]; then
            echo "Job passed!"
            exit 0
          else
            echo "Job failed!"
            exit 1
          fi

      - name: Report success back
        if: success() && github.event.client_payload.source_commit_sha != '' && github.event.client_payload.source_commit_sha != null
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.PAT_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.event.client_payload.source_repository}}/statuses/${{ github.event.client_payload.source_commit_sha }} \
            -d '{
                "state": "success",
                "context": "Playwright Tests",
                "description": "Playwright Tests Passed!",
                "target_url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
              }'

      - name: Report failure back
        if: failure() && github.event.client_payload.source_commit_sha != '' && github.event.client_payload.source_commit_sha != null
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.PAT_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.event.client_payload.source_repository}}/statuses/${{ github.event.client_payload.source_commit_sha }} \
            -d '{
                "state": "failure",
                "context": "Playwright Tests",
                "description": "Playwright Tests Failed!",
                "target_url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
              }'